version: "3"
services:
  main: 
    build:
      context: .
    volumes: 
    - ./:/srv
    stdin_open: true
    tty: true
    environment:
      - TZ=America/New_York
      - DEBIAN_FRONTEND=noninteractive
